version: 2

build:
  os: ubuntu-24.04
  tools:
    nodejs: "20"
    python: "3.12"
  commands:
    - pip install -e ".[docs]"
    - jupyter-book build --html --ci
    - mkdir --parents $READTHEDOCS_OUTPUT/html
    - cp --recursive _build/html/* $READTHEDOCS_OUTPUT/html
    - rm -rf _build